// Datos centralizados de emojis para uso en toda la aplicación

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: string[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Frecuentes',
    icon: '⭐',
    emojis: ['📝', '⏰', '✅', '🛏️', '🍔', 
             '😀', '😊', '😎', '🤩', '😍', '🤔', '😴', '🥳', '😇', '🤯', 
             '📅', '📌', '🔑', '📚', '💻', '📱', '🔋',
             '🏋️', '🚴', '🚗', '🍎', '🍕', '🛒', '☕', '🍷', '🎵', '🎮', '🎨', '✈️',
             '👍', '👎', '👏', '🙌', '🤝', '💪', '✋', '👋', '🖐️', '✌️', '🤞', '🙏']
  },
  {
    name: 'Sonrisas y Emociones',
    icon: '😀',
    emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '😚', '😙', '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨', '😐', '😑', '😶', '🫥', '😏', '😒', '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🤧', '🥵', '🥶', '🥴', '😵', '😵‍💫', '🤯', '🤠', '🥳', '🥸', '😎', '🤓', '🧐', '😕', '🫤', '😟', '🙁', '☹️', '😮', '😯', '😲', '😳', '🥺', '🥹', '😦', '😧', '😨', '😰', '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫', '🥱', '😤', '😠', '😡', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '👾', '🤖', '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿', '😾']
  },
  {
    name: 'Manos y Gestos',
    icon: '👋',
    emojis: ['👋', '🤚', '🖐️', '✋', '🖖', '🫱', '🫲', '🫳', '🫴', '👌', '🤌', '🤏', '✌️', '🤞', '🫰', '🤟', '🤘', '🤙', '👈', '👉', '👆', '🖕', '👇', '☝️', '🫵', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏', '🙌', '🫶', '👐', '🤲', '🤝', '🙏', '✍️', '💅', '🤳', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻', '👃', '🧠', '🫀', '🫁', '🦷', '🦴', '👀', '👁️', '👅', '👄', '🫦', '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔', '👩', '🧓', '👴', '👵', '🙍', '🙎', '🙅', '🙆', '💁', '🙋', '🧏', '🙇', '🤦', '🤷', '👮', '🕵️', '💂', '🥷', '👷', '🫅', '🤴', '👸', '👳', '👲', '🧕', '🤵', '👰', '🤰', '🫃', '🫄', '🤱', '👼', '🎅', '🤶', '🦸', '🦹', '🧙', '🧚', '🧛', '🧜', '🧝', '🧞', '🧟', '🧌', '💆', '💇', '🚶', '🧍', '🧎', '🏃', '💃', '🕺', '🕴️', '👯', '🧖', '🧗', '🤸', '🏌️', '🏇', '⛷️', '🏂', '🏋️', '🤼', '🤽', '🤾', '🤺', '⛹️', '🏊', '🚣', '🧘', '🛀', '🛌']
  },
  {
    name: 'Objetos',
    icon: '📦',
    emojis: ['⌚', '📱', '📲', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '🖲️', '🕹️', '🗜️', '💽', '💾', '💿', '📀', '📼', '📷', '📸', '📹', '🎥', '📽️', '🎞️', '📞', '☎️', '📟', '📠', '📺', '📻', '🎙️', '🎚️', '🎛️', '🧭', '⏱️', '⏲️', '⏰', '🕰️', '⌛', '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯️', '🪔', '🧯', '🛢️', '💸', '💵', '💴', '💶', '💷', '🪙', '💰', '💳', '💎', '⚖️', '🪜', '🧰', '🪛', '🔧', '🔨', '⚒️', '🛠️', '⛏️', '🪚', '🔩', '⚙️', '🪤', '🧱', '⛓️', '🧲', '🔫', '💣', '🧨', '🪓', '🔪', '🗡️', '⚔️', '🛡️', '🚬', '⚰️', '🪦', '⚱️', '🏺', '🔮', '📿', '🧿', '💈', '⚗️', '🔭', '🔬', '🕳️', '🩹', '🩺', '💊', '💉', '🩸', '🧬', '🦠', '🧫', '🧪', '🌡️', '🧹', '🪠', '🧺', '🧻', '🚽', '🚰', '🚿', '🛁', '🛀', '🧼', '🪥', '🪒', '🧽', '🪣', '🧴', '🛎️', '🔑', '🗝️', '🚪', '🪑', '🛋️', '🛏️', '🛌', '🧸', '🪆', '🖼️', '🪞', '🪟', '🛍️', '🛒', '🎁', '🎈', '🎏', '🎀', '🪄', '🪅', '🎊', '🎉', '🎎', '🏮', '🎐', '🧧', '✉️', '📩', '📨', '📧', '💌', '📥', '📤', '📦', '🏷️', '🪧', '📪', '📫', '📬', '📭', '📮', '📯', '📜', '📃', '📄', '📑', '🧾', '📊', '📈', '📉', '🗒️', '🗓️', '📆', '📅', '🗑️', '📇', '🗃️', '🗳️', '🗄️', '📋', '📁', '📂', '🗂️', '🗞️', '📰', '📓', '📔', '📒', '📕', '📗', '📘', '📙', '📚', '📖', '🔖', '🧷', '🔗', '📎', '🖇️', '📐', '📏', '🧮', '📌', '📍', '✂️', '🖊️', '🖋️', '✒️', '🖌️', '🖍️', '📝', '✏️', '🔍', '🔎', '🔏', '🔐', '🔒', '🔓']
  },
  {
    name: 'Comida',
    icon: '🍔',
    emojis: ['🍇', '🍈', '🍉', '🍊', '🍋', '🍌', '🍍', '🥭', '🍎', '🍏', '🍐', '🍑', '🍒', '🍓', '🫐', '🥝', '🍅', '🫒', '🥥', '🥑', '🍆', '🥔', '🥕', '🌽', '🌶️', '🫑', '🥒', '🥬', '🥦', '🧄', '🧅', '🍄', '🥜', '🫘', '🌰', '🍞', '🥐', '🥖', '🫓', '🥨', '🥯', '🥞', '🧇', '🧀', '🍖', '🍗', '🥩', '🥓', '🍔', '🍟', '🍕', '🌭', '🥪', '🌮', '🌯', '🫔', '🥙', '🧆', '🥚', '🍳', '🥘', '🍲', '🫕', '🥣', '🥗', '🍿', '🧈', '🧂', '🥫', '🍱', '🍘', '🍙', '🍚', '🍛', '🍜', '🍝', '🍠', '🍢', '🍣', '🍤', '🍥', '🥮', '🍡', '🥟', '🥠', '🥡', '🦀', '🦞', '🦐', '🦑', '🦪', '🍦', '🍧', '🍨', '🍩', '🍪', '🎂', '🍰', '🧁', '🥧', '🍫', '🍬', '🍭', '🍮', '🍯', '🍼', '🥛', '☕', '🫖', '🍵', '🍶', '🍾', '🍷', '🍸', '🍹', '🍺', '🍻', '🥂', '🥃', '🫗', '🥤', '🧋', '🧃', '🧉', '🧊', '🥢', '🍽️', '🍴', '🥄', '🔪', '🫙', '🏺']
  },
  {
    name: 'Actividades',
    icon: '⚽',
    emojis: ['⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳', '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛼', '🛷', '⛸️', '🥌', '🎿', '⛷️', '🏂', '🪂', '🏋️', '🏋️‍♂️', '🏋️‍♀️', '🤼', '🤼‍♂️', '🤼‍♀️', '🤸', '🤸‍♂️', '🤸‍♀️', '⛹️', '⛹️‍♂️', '⛹️‍♀️', '🤺', '🤾', '🤾‍♂️', '🤾‍♀️', '🏌️', '🏌️‍♂️', '🏌️‍♀️', '🏇', '🧘', '🧘‍♂️', '🧘‍♀️', '🏄', '🏄‍♂️', '🏄‍♀️', '🏊', '🏊‍♂️', '🏊‍♀️', '🤽', '🤽‍♂️', '🤽‍♀️', '🚣', '🚣‍♂️', '🚣‍♀️', '🧗', '🧗‍♂️', '🧗‍♀️', '🚵', '🚵‍♂️', '🚵‍♀️', '🚴', '🚴‍♂️', '🚴‍♀️', '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏵️', '🎗️', '🎫', '🎟️', '🎪', '🤹', '🤹‍♂️', '🤹‍♀️', '🎭', '🩰', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹', '🥁', '🪘', '🎷', '🎺', '🪗', '🎸', '🪕', '🎻', '🎲', '♟️', '🎯', '🎳', '🎮', '🎰', '🧩']
  },
  {
    name: 'Viajes',
    icon: '✈️',
    emojis: ['🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🦯', '🦽', '🦼', '🛴', '🚲', '🛵', '🏍️', '🛺', '🚨', '🚔', '🚍', '🚘', '🚖', '🚡', '🚠', '🚟', '🚃', '🚋', '🚞', '🚝', '🚄', '🚅', '🚈', '🚂', '🚆', '🚇', '🚊', '🚉', '✈️', '🛫', '🛬', '🛩️', '💺', '🛰️', '🚀', '🛸', '🚁', '🛶', '⛵', '🚤', '🛥️', '🛳️', '⛴️', '🚢', '⚓', '🪝', '⛽', '🚧', '🚦', '🚥', '🚏', '🗺️', '🗿', '🗽', '🗼', '🏰', '🏯', '🏟️', '🎡', '🎢', '🎠', '⛲', '⛱️', '🏖️', '🏝️', '🏜️', '🌋', '⛰️', '🏔️', '🗻', '🏕️', '⛺', '🛖', '🏠', '🏡', '🏘️', '🏚️', '🏗️', '🏭', '🏢', '🏬', '🏣', '🏤', '🏥', '🏦', '🏨', '🏪', '🏫', '🏩', '💒', '🏛️', '⛪', '🕌', '🕍', '🛕', '🕋', '⛩️', '🛤️', '🛣️', '🗾', '🎑', '🏞️', '🌅', '🌄', '🌠', '🎇', '🎆', '🌇', '🌆', '🏙️', '🌃', '🌌', '🌉', '🌁']
  },
  {
    name: 'Simbolos',
    icon: '❤️',
    emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮️', '✝️', '☪️', '🕉️', '☸️', '✡️', '🔯', '🕎', '☯️', '☦️', '🛐', '⛎', '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '🆔', '⚛️', '🉑', '☢️', '☣️', '📴', '📳', '🈶', '🈚', '🈸', '🈺', '🈷️', '✴️', '🆚', '💮', '🉐', '㊙️', '㊗️', '🈴', '🈵', '🈹', '🈲', '🅰️', '🅱️', '🆎', '🆑', '🅾️', '🆘', '❌', '⭕', '🛑', '⛔', '📛', '🚫', '💯', '💢', '♨️', '🚷', '🚯', '🚳', '🚱', '🔞', '📵', '🚭', '❗', '❕', '❓', '❔', '‼️', '⁉️', '🔅', '🔆', '〽️', '⚠️', '🚸', '🔱', '⚜️', '🔰', '♻️', '✅', '🈯', '💹', '❇️', '✳️', '❎', '🌐', '💠', 'Ⓜ️', '🌀', '💤', '🏧', '🚾', '♿', '🅿️', '🛗', '🈳', '🈂️', '🛂', '🛃', '🛄', '🛅', '🚹', '🚺', '🚼', '⚧', '🚻', '🚮', '🎦', '📶', '🈁', '🔣', 'ℹ️', '🔤', '🔡', '🔠', '🆖', '🆗', '🆙', '🆒', '🆕', '🆓', '0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣', '🔟', '🔢', '#️⃣', '*️⃣', '⏏️', '▶️', '⏸️', '⏯️', '⏹️', '⏺️', '⏭️', '⏮️', '⏩', '⏪', '⏫', '⏬', '◀️', '🔼', '🔽', '➡️', '⬅️', '⬆️', '⬇️', '↗️', '↘️', '↙️', '↖️', '↕️', '↔️', '↪️', '↩️', '⤴️', '⤵️', '🔀', '🔁', '🔂', '🔄', '🔃', '🎵', '🎶', '➕', '➖', '➗', '✖️', '♾️', '💲', '💱', '™️', '©️', '®️', '👁️‍🗨️', '🔚', '🔙', '🔛', '🔝', '🔜', '〰️', '➰', '➿', '✔️', '☑️', '🔘', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '⚫', '⚪', '🟤', '🔺', '🔻', '🔸', '🔹', '🔶', '🔷', '🔳', '🔲', '▪️', '▫️', '◾', '◽', '◼️', '◻️', '🟥', '🟧', '🟨', '🟩', '🟦', '🟪', '⬛', '⬜', '🟫', '🔈', '🔇', '🔉', '🔊', '🔔', '🔕', '📣', '📢', '💬', '💭', '🗯️', '♠️', '♣️', '♥️', '♦️', '🃏', '🎴', '🀄', '🕐', '🕑', '🕒', '🕓', '🕔', '🕕', '🕖', '🕗', '🕘', '🕙', '🕚', '🕛', '🕜', '🕝', '🕞', '🕟', '🕠', '🕡', '🕢', '🕣', '🕤', '🕥', '🕦', '🕧']
  }
];

export const EMOJI_KEYWORDS: { [emoji: string]: string[] } = {
  // Frecuentes
  '📝': ['note', 'nota', 'write', 'escribir', 'memo', 'tarea', 'task'],
  '⏰': ['alarm', 'alarma', 'clock', 'reloj', 'time', 'tiempo', 'hora'],
  '✅': ['check', 'done', 'hecho', 'completado', 'listo', 'ok', 'ready'],
  '🛏️': ['bed', 'cama', 'sleep', 'dormir', 'rest', 'descanso', 'nap', 'siesta'],
  '📅': ['calendar', 'calendario', 'date', 'fecha', 'schedule', 'agenda'],
  '📌': ['pin', 'chincheta', 'mark', 'marcar', 'important', 'importante'],
  '🔑': ['key', 'llave', 'password', 'contraseña', 'access', 'acceso'],
  '📚': ['books', 'libros', 'study', 'estudiar', 'read', 'leer', 'learn', 'aprender'],
  '💻': ['laptop', 'computer', 'computadora', 'work', 'trabajo', 'code', 'codigo', 'programar'],
  '📱': ['phone', 'telefono', 'mobile', 'celular', 'call', 'llamar'],
  '🔋': ['battery', 'bateria', 'charge', 'cargar', 'energy', 'energia'],
  '🏋️': ['gym', 'gimnasio', 'exercise', 'ejercicio', 'workout', 'entrenar', 'fitness'],
  '🚴': ['bike', 'bicicleta', 'cycling', 'ciclismo', 'ride', 'montar'],
  '🚗': ['car', 'carro', 'auto', 'drive', 'manejar', 'conducir', 'vehicle', 'vehiculo'],
  '🍎': ['apple', 'manzana', 'fruit', 'fruta', 'healthy', 'saludable'],
  '🍕': ['pizza', 'food', 'comida', 'eat', 'comer', 'dinner', 'cena'],
  '🛒': ['cart', 'carrito', 'shopping', 'compras', 'buy', 'comprar', 'store', 'tienda'],
  '☕': ['coffee', 'cafe', 'drink', 'bebida', 'morning', 'mañana', 'break', 'descanso'],
  '🍷': ['wine', 'vino', 'drink', 'bebida', 'alcohol', 'celebrate', 'celebrar'],
  '🎵': ['music', 'musica', 'song', 'cancion', 'listen', 'escuchar', 'audio'],
  '🎮': ['game', 'juego', 'play', 'jugar', 'gaming', 'videogame', 'videojuego'],
  '🎨': ['art', 'arte', 'paint', 'pintar', 'draw', 'dibujar', 'creative', 'creativo'],
  '✈️': ['plane', 'avion', 'travel', 'viajar', 'flight', 'vuelo', 'trip', 'viaje'],
  
  // Dinero y finanzas
  '💵': ['money', 'dinero', 'dollar', 'dolar', 'cash', 'efectivo', 'billete', 'bill', 'pay', 'pagar'],
  '💴': ['money', 'dinero', 'yen', 'cash', 'efectivo', 'billete', 'bill', 'japan', 'japon'],
  '💶': ['money', 'dinero', 'euro', 'cash', 'efectivo', 'billete', 'bill', 'europe', 'europa'],
  '💷': ['money', 'dinero', 'pound', 'libra', 'cash', 'efectivo', 'billete', 'bill', 'uk', 'england'],
  '💰': ['money', 'dinero', 'bag', 'bolsa', 'rich', 'rico', 'cash', 'efectivo', 'savings', 'ahorros'],
  '💳': ['card', 'tarjeta', 'credit', 'credito', 'debit', 'debito', 'pay', 'pagar', 'bank', 'banco'],
  '🪙': ['coin', 'moneda', 'money', 'dinero', 'gold', 'oro', 'change', 'cambio'],
  '💸': ['money', 'dinero', 'flying', 'volando', 'spend', 'gastar', 'expense', 'gasto', 'cash', 'efectivo'],
  '💎': ['diamond', 'diamante', 'gem', 'gema', 'jewel', 'joya', 'rich', 'rico', 'luxury', 'lujo'],
  '🏦': ['bank', 'banco', 'money', 'dinero', 'finance', 'finanzas', 'building', 'edificio'],
  
  // Playa y vacaciones
  '🏖️': ['beach', 'playa', 'vacation', 'vacaciones', 'sand', 'arena', 'summer', 'verano', 'holiday'],
  '🏝️': ['island', 'isla', 'beach', 'playa', 'tropical', 'paradise', 'paraiso', 'vacation', 'vacaciones'],
  '🌊': ['wave', 'ola', 'sea', 'mar', 'ocean', 'oceano', 'beach', 'playa', 'water', 'agua', 'surf'],
  '🏄': ['surf', 'surfing', 'surfear', 'beach', 'playa', 'wave', 'ola', 'sport', 'deporte'],
  '⛱️': ['umbrella', 'sombrilla', 'beach', 'playa', 'sun', 'sol', 'vacation', 'vacaciones'],
  '🐚': ['shell', 'concha', 'beach', 'playa', 'sea', 'mar', 'ocean', 'oceano'],
  '🦀': ['crab', 'cangrejo', 'beach', 'playa', 'sea', 'mar', 'seafood', 'marisco'],
  '🦞': ['lobster', 'langosta', 'seafood', 'marisco', 'beach', 'playa', 'sea', 'mar'],
  '🌴': ['palm', 'palma', 'tree', 'arbol', 'tropical', 'beach', 'playa', 'vacation', 'vacaciones'],
  '🥥': ['coconut', 'coco', 'tropical', 'beach', 'playa', 'fruit', 'fruta'],
  '🍹': ['cocktail', 'coctel', 'drink', 'bebida', 'tropical', 'beach', 'playa', 'vacation', 'vacaciones'],
  
  // Sol y clima
  '☀️': ['sun', 'sol', 'sunny', 'soleado', 'hot', 'caliente', 'summer', 'verano', 'weather', 'clima'],
  '🌤️': ['sun', 'sol', 'cloud', 'nube', 'weather', 'clima', 'partly', 'parcialmente'],
  '⛅': ['cloud', 'nube', 'sun', 'sol', 'weather', 'clima'],
  '🌧️': ['rain', 'lluvia', 'cloud', 'nube', 'weather', 'clima', 'rainy', 'lluvioso'],
  '⛈️': ['storm', 'tormenta', 'thunder', 'trueno', 'rain', 'lluvia', 'weather', 'clima'],
  '🌈': ['rainbow', 'arcoiris', 'colors', 'colores', 'weather', 'clima', 'hope', 'esperanza'],
  '❄️': ['snow', 'nieve', 'cold', 'frio', 'winter', 'invierno', 'ice', 'hielo', 'freeze', 'congelar'],
  '🌙': ['moon', 'luna', 'night', 'noche', 'sleep', 'dormir', 'dark', 'oscuro'],
  '⭐': ['star', 'estrella', 'night', 'noche', 'sky', 'cielo', 'favorite', 'favorito'],
  
  // Emociones
  '😀': ['happy', 'feliz', 'smile', 'sonrisa', 'joy', 'alegria'],
  '😃': ['happy', 'feliz', 'smile', 'sonrisa', 'joy', 'alegria', 'excited', 'emocionado'],
  '😄': ['happy', 'feliz', 'smile', 'sonrisa', 'laugh', 'reir', 'joy', 'alegria'],
  '😁': ['happy', 'feliz', 'grin', 'sonrisa', 'teeth', 'dientes'],
  '😊': ['smile', 'sonrisa', 'happy', 'feliz', 'cute', 'lindo', 'blush', 'sonrojado'],
  '😎': ['cool', 'genial', 'sunglasses', 'gafas', 'awesome', 'increible'],
  '🤩': ['star', 'estrella', 'excited', 'emocionado', 'amazing', 'asombroso', 'wow'],
  '😍': ['love', 'amor', 'heart', 'corazon', 'like', 'gustar', 'crush', 'enamorado'],
  '🥰': ['love', 'amor', 'heart', 'corazon', 'cute', 'lindo', 'sweet', 'dulce'],
  '🤔': ['think', 'pensar', 'wonder', 'preguntarse', 'hmm', 'curious', 'curioso'],
  '😴': ['sleep', 'dormir', 'tired', 'cansado', 'zzz', 'nap', 'siesta', 'sleepy'],
  '😪': ['sleepy', 'somnoliento', 'tired', 'cansado', 'sleep', 'dormir'],
  '🥳': ['party', 'fiesta', 'celebrate', 'celebrar', 'birthday', 'cumpleaños'],
  '😇': ['angel', 'angel', 'innocent', 'inocente', 'good', 'bueno', 'blessed'],
  '🤯': ['mind', 'mente', 'blown', 'explotado', 'shocked', 'impactado', 'wow'],
  '😢': ['sad', 'triste', 'cry', 'llorar', 'tear', 'lagrima'],
  '😭': ['cry', 'llorar', 'sad', 'triste', 'tears', 'lagrimas', 'weep'],
  '😔': ['sad', 'triste', 'pensive', 'pensativo', 'disappointed', 'decepcionado'],
  '😰': ['anxious', 'ansioso', 'worried', 'preocupado', 'nervous', 'nervioso', 'sweat', 'sudor'],
  '😱': ['scared', 'asustado', 'fear', 'miedo', 'shock', 'horror', 'scream', 'gritar'],
  '😠': ['angry', 'enojado', 'mad', 'furioso', 'molesto', 'enfadado'],
  '😡': ['angry', 'enojado', 'mad', 'furioso', 'rage', 'rabia', 'molesto'],
  '😤': ['angry', 'enojado', 'frustrated', 'frustrado', 'huff', 'resoplar'],
  '🤬': ['angry', 'enojado', 'curse', 'maldecir', 'swear', 'furioso'],
  '😈': ['devil', 'diablo', 'evil', 'malo', 'mischief', 'travesura'],
  '👿': ['devil', 'diablo', 'angry', 'enojado', 'evil', 'malo'],
  '💀': ['skull', 'calavera', 'dead', 'muerto', 'death', 'muerte'],
  '☠️': ['skull', 'calavera', 'danger', 'peligro', 'death', 'muerte'],
  '💩': ['poop', 'caca', 'poo', 'funny', 'gracioso', 'joke', 'broma'],
  '🤡': ['clown', 'payaso', 'funny', 'gracioso', 'circus', 'circo'],
  '👹': ['ogre', 'ogro', 'monster', 'monstruo', 'demon', 'demonio'],
  '👺': ['goblin', 'duende', 'tengu', 'monster', 'monstruo'],
  '👻': ['ghost', 'fantasma', 'boo', 'spooky', 'espeluznante', 'halloween'],
  '👽': ['alien', 'extraterrestre', 'ufo', 'ovni', 'space', 'espacio'],
  '👾': ['alien', 'extraterrestre', 'game', 'juego', 'monster', 'monstruo'],
  '🤖': ['robot', 'bot', 'machine', 'maquina', 'tech', 'tecnologia'],
  
  // Amor y corazones
  '❤️': ['heart', 'corazon', 'love', 'amor', 'red', 'rojo'],
  '🧡': ['heart', 'corazon', 'love', 'amor', 'orange', 'naranja'],
  '💛': ['heart', 'corazon', 'love', 'amor', 'yellow', 'amarillo'],
  '💚': ['heart', 'corazon', 'love', 'amor', 'green', 'verde'],
  '💙': ['heart', 'corazon', 'love', 'amor', 'blue', 'azul'],
  '💜': ['heart', 'corazon', 'love', 'amor', 'purple', 'morado'],
  '🖤': ['heart', 'corazon', 'love', 'amor', 'black', 'negro'],
  '🤍': ['heart', 'corazon', 'love', 'amor', 'white', 'blanco'],
  '💔': ['heart', 'corazon', 'broken', 'roto', 'sad', 'triste', 'breakup', 'ruptura'],
  '💕': ['hearts', 'corazones', 'love', 'amor', 'cute', 'lindo'],
  '💘': ['heart', 'corazon', 'love', 'amor', 'cupid', 'arrow', 'flecha'],
  '💝': ['heart', 'corazon', 'gift', 'regalo', 'love', 'amor'],
  
  // Comida (nota: las claves duplicadas fueron removidas de las líneas 171-381)
  '🍔': ['burger', 'hamburguesa', 'food', 'comida', 'eat', 'comer', 'fast', 'rapido'],
  '🍟': ['fries', 'papas', 'french', 'food', 'comida', 'fast', 'rapido'],
  '🌮': ['taco', 'tacos', 'mexican', 'mexicano', 'food', 'comida'],
  '🌯': ['burrito', 'wrap', 'mexican', 'mexicano', 'food', 'comida'],
  '🍣': ['sushi', 'japanese', 'japones', 'food', 'comida', 'fish', 'pescado'],
  '🍜': ['noodles', 'fideos', 'ramen', 'asian', 'asiatico', 'food', 'comida', 'soup', 'sopa'],
  '🍝': ['pasta', 'spaghetti', 'espagueti', 'italian', 'italiano', 'food', 'comida'],
  '🥗': ['salad', 'ensalada', 'healthy', 'saludable', 'vegetable', 'vegetal', 'food', 'comida'],
  '🍖': ['meat', 'carne', 'food', 'comida', 'bbq', 'asado'],
  '🥩': ['steak', 'bistec', 'meat', 'carne', 'food', 'comida', 'beef', 'res'],
  '🍗': ['chicken', 'pollo', 'food', 'comida', 'meat', 'carne'],
  '🥚': ['egg', 'huevo', 'food', 'comida', 'breakfast', 'desayuno'],
  '🍳': ['egg', 'huevo', 'fried', 'frito', 'breakfast', 'desayuno', 'cook', 'cocinar'],
  '🥞': ['pancake', 'panqueque', 'breakfast', 'desayuno', 'food', 'comida'],
  '🍞': ['bread', 'pan', 'food', 'comida', 'bakery', 'panaderia'],
  '🥐': ['croissant', 'cuernito', 'bread', 'pan', 'breakfast', 'desayuno', 'french', 'frances'],
  '🍰': ['cake', 'pastel', 'dessert', 'postre', 'birthday', 'cumpleaños', 'sweet', 'dulce'],
  '🧁': ['cupcake', 'pastelito', 'dessert', 'postre', 'sweet', 'dulce'],
  '🍩': ['donut', 'dona', 'dessert', 'postre', 'sweet', 'dulce'],
  '🍪': ['cookie', 'galleta', 'dessert', 'postre', 'sweet', 'dulce'],
  '🍫': ['chocolate', 'candy', 'dulce', 'sweet'],
  '🍬': ['candy', 'dulce', 'sweet', 'caramelo'],
  '🍭': ['lollipop', 'paleta', 'candy', 'dulce', 'sweet'],
  '🍦': ['ice cream', 'helado', 'dessert', 'postre', 'cold', 'frio', 'summer', 'verano'],
  
  // Frutas y verduras
  '🍏': ['apple', 'manzana', 'fruit', 'fruta', 'green', 'verde', 'healthy', 'saludable'],
  '🍊': ['orange', 'naranja', 'fruit', 'fruta', 'citrus', 'citrico'],
  '🍋': ['lemon', 'limon', 'fruit', 'fruta', 'citrus', 'citrico', 'yellow', 'amarillo'],
  '🍌': ['banana', 'platano', 'fruit', 'fruta', 'yellow', 'amarillo'],
  '🍇': ['grape', 'uva', 'fruit', 'fruta', 'wine', 'vino', 'purple', 'morado'],
  '🍓': ['strawberry', 'fresa', 'fruit', 'fruta', 'red', 'rojo', 'berry'],
  '🍉': ['watermelon', 'sandia', 'fruit', 'fruta', 'summer', 'verano'],
  '🍑': ['peach', 'durazno', 'fruit', 'fruta'],
  '🍒': ['cherry', 'cereza', 'fruit', 'fruta', 'red', 'rojo'],
  '🥑': ['avocado', 'aguacate', 'fruit', 'fruta', 'healthy', 'saludable', 'green', 'verde'],
  '🥕': ['carrot', 'zanahoria', 'vegetable', 'vegetal', 'orange', 'naranja'],
  '🥦': ['broccoli', 'brocoli', 'vegetable', 'vegetal', 'green', 'verde', 'healthy', 'saludable'],
  '🥬': ['lettuce', 'lechuga', 'vegetable', 'vegetal', 'salad', 'ensalada', 'green', 'verde'],
  '🍄': ['mushroom', 'hongo', 'champinon', 'vegetable', 'vegetal'],
  '🌽': ['corn', 'maiz', 'elote', 'vegetable', 'vegetal', 'yellow', 'amarillo'],
  '🥔': ['potato', 'papa', 'patata', 'vegetable', 'vegetal'],
  '🍆': ['eggplant', 'berenjena', 'vegetable', 'vegetal', 'purple', 'morado'],
  '🌶️': ['pepper', 'chile', 'hot', 'picante', 'spicy', 'red', 'rojo'],
  '🧄': ['garlic', 'ajo', 'vegetable', 'vegetal', 'cook', 'cocinar'],
  '🧅': ['onion', 'cebolla', 'vegetable', 'vegetal', 'cook', 'cocinar'],
  
  // Bebidas
  '🍵': ['tea', 'te', 'drink', 'bebida', 'hot', 'caliente', 'green', 'verde'],
  '🥤': ['soda', 'refresco', 'drink', 'bebida', 'cold', 'frio', 'cup', 'vaso'],
  '🧃': ['juice', 'jugo', 'drink', 'bebida', 'box', 'caja'],
  '🥛': ['milk', 'leche', 'drink', 'bebida', 'white', 'blanco'],
  '🍺': ['beer', 'cerveza', 'drink', 'bebida', 'alcohol', 'bar'],
  '🍻': ['beer', 'cerveza', 'cheers', 'salud', 'drink', 'bebida', 'bar', 'celebrate', 'celebrar'],
  '🥂': ['champagne', 'champan', 'cheers', 'salud', 'celebrate', 'celebrar', 'toast', 'brindis'],
  '🍸': ['cocktail', 'coctel', 'drink', 'bebida', 'martini', 'bar'],
  
  // Transporte
  '🚕': ['taxi', 'cab', 'car', 'carro', 'ride', 'viaje'],
  '🚌': ['bus', 'autobus', 'camion', 'transport', 'transporte', 'public', 'publico'],
  '🚎': ['trolley', 'tranvia', 'bus', 'autobus', 'transport', 'transporte'],
  '🏎️': ['race', 'carrera', 'car', 'carro', 'fast', 'rapido', 'speed', 'velocidad'],
  '🚓': ['police', 'policia', 'car', 'carro', 'cop', 'emergency', 'emergencia'],
  '🚑': ['ambulance', 'ambulancia', 'emergency', 'emergencia', 'hospital', 'medical', 'medico'],
  '🚒': ['fire', 'fuego', 'truck', 'camion', 'emergency', 'emergencia', 'firefighter', 'bombero'],
  '🛻': ['truck', 'camioneta', 'pickup', 'vehicle', 'vehiculo'],
  '🚚': ['truck', 'camion', 'delivery', 'entrega', 'move', 'mudanza'],
  '🚲': ['bike', 'bicicleta', 'bicycle', 'ride', 'montar', 'cycle', 'exercise', 'ejercicio'],
  '🏍️': ['motorcycle', 'moto', 'motocicleta', 'bike', 'ride', 'montar'],
  '🛵': ['scooter', 'moto', 'vespa', 'ride', 'montar'],
  '🚀': ['rocket', 'cohete', 'space', 'espacio', 'launch', 'lanzar', 'fast', 'rapido'],
  '🛸': ['ufo', 'ovni', 'alien', 'extraterrestre', 'space', 'espacio'],
  '🚁': ['helicopter', 'helicoptero', 'fly', 'volar', 'air', 'aire'],
  '⛵': ['boat', 'bote', 'sail', 'vela', 'ship', 'barco', 'sea', 'mar'],
  '🚢': ['ship', 'barco', 'boat', 'bote', 'cruise', 'cruiser', 'sea', 'mar'],
  '🚂': ['train', 'tren', 'transport', 'transporte', 'travel', 'viajar'],
  '🚇': ['metro', 'subway', 'train', 'tren', 'underground', 'subterraneo'],
  
  // Naturaleza (nota: se removió la entrada duplicada de 🌴 que estaba en la línea 315)
  
  // Deportes
  '⚽': ['soccer', 'futbol', 'football', 'ball', 'balon', 'sport', 'deporte'],
  '🏀': ['basketball', 'basquetbol', 'ball', 'balon', 'sport', 'deporte', 'nba'],
  '🏈': ['football', 'americano', 'ball', 'balon', 'sport', 'deporte', 'nfl'],
  '⚾': ['baseball', 'beisbol', 'ball', 'pelota', 'sport', 'deporte'],
  '🎾': ['tennis', 'tenis', 'ball', 'pelota', 'sport', 'deporte', 'racket', 'raqueta'],
  '🏐': ['volleyball', 'voleibol', 'ball', 'balon', 'sport', 'deporte'],
  '🎱': ['pool', 'billar', 'ball', 'bola', 'game', 'juego'],
  '🏓': ['ping pong', 'table tennis', 'tenis de mesa', 'sport', 'deporte'],
  '🏸': ['badminton', 'sport', 'deporte', 'racket', 'raqueta'],
  '🥊': ['boxing', 'boxeo', 'fight', 'pelea', 'sport', 'deporte'],
  '🥋': ['martial arts', 'artes marciales', 'karate', 'judo', 'sport', 'deporte'],
  '⛳': ['golf', 'sport', 'deporte', 'ball', 'pelota'],
  '🏆': ['trophy', 'trofeo', 'winner', 'ganador', 'champion', 'campeon', 'prize', 'premio'],
  '🥇': ['gold', 'oro', 'medal', 'medalla', 'first', 'primero', 'winner', 'ganador'],
  '🥈': ['silver', 'plata', 'medal', 'medalla', 'second', 'segundo'],
  '🥉': ['bronze', 'bronce', 'medal', 'medalla', 'third', 'tercero'],
  
  // Animales
  '🐶': ['dog', 'perro', 'puppy', 'cachorro', 'pet', 'mascota', 'animal'],
  '🐱': ['cat', 'gato', 'kitten', 'gatito', 'pet', 'mascota', 'animal'],
  '🐭': ['mouse', 'raton', 'animal', 'pet', 'mascota'],
  '🐹': ['hamster', 'hamster', 'pet', 'mascota', 'animal', 'cute', 'lindo'],
  '🐰': ['rabbit', 'conejo', 'bunny', 'conejito', 'pet', 'mascota', 'animal'],
  '🦊': ['fox', 'zorro', 'animal', 'wild', 'salvaje'],
  '🐻': ['bear', 'oso', 'animal', 'wild', 'salvaje'],
  '🐼': ['panda', 'animal', 'bear', 'oso', 'cute', 'lindo'],
  '🐨': ['koala', 'animal', 'australia', 'cute', 'lindo'],
  '🦁': ['lion', 'leon', 'animal', 'wild', 'salvaje', 'king', 'rey'],
  '🐯': ['tiger', 'tigre', 'animal', 'wild', 'salvaje'],
  '🐮': ['cow', 'vaca', 'animal', 'farm', 'granja'],
  '🐷': ['pig', 'cerdo', 'puerco', 'animal', 'farm', 'granja'],
  '🐔': ['chicken', 'pollo', 'gallina', 'animal', 'farm', 'granja'],
  '🐦': ['bird', 'pajaro', 'ave', 'animal', 'fly', 'volar'],
  '🦅': ['eagle', 'aguila', 'bird', 'pajaro', 'animal', 'fly', 'volar'],
  '🦆': ['duck', 'pato', 'bird', 'pajaro', 'animal'],
  '🦉': ['owl', 'buho', 'bird', 'pajaro', 'animal', 'night', 'noche', 'wise', 'sabio'],
  '🐴': ['horse', 'caballo', 'animal', 'ride', 'montar'],
  '🦄': ['unicorn', 'unicornio', 'magic', 'magico', 'fantasy', 'fantasia'],
  '🐟': ['fish', 'pez', 'pescado', 'animal', 'sea', 'mar', 'water', 'agua'],
  '🐬': ['dolphin', 'delfin', 'animal', 'sea', 'mar', 'ocean', 'oceano'],
  '🦈': ['shark', 'tiburon', 'animal', 'sea', 'mar', 'ocean', 'oceano', 'danger', 'peligro'],
  '🐙': ['octopus', 'pulpo', 'animal', 'sea', 'mar', 'ocean', 'oceano'],
  '🦋': ['butterfly', 'mariposa', 'insect', 'insecto', 'animal', 'beautiful', 'hermoso'],
  '🐝': ['bee', 'abeja', 'insect', 'insecto', 'animal', 'honey', 'miel'],
  '🐛': ['bug', 'bicho', 'insect', 'insecto', 'animal', 'caterpillar', 'oruga'],
  '🐌': ['snail', 'caracol', 'animal', 'slow', 'lento'],
  '🦎': ['lizard', 'lagartija', 'animal', 'reptile', 'reptil'],
  '🐢': ['turtle', 'tortuga', 'animal', 'slow', 'lento', 'sea', 'mar'],
  '🐍': ['snake', 'serpiente', 'vibora', 'animal', 'reptile', 'reptil'],
  
  '🌸': ['flower', 'flor', 'cherry', 'cerezo', 'pink', 'rosa', 'spring', 'primavera', 'blossom'],
  '🌺': ['flower', 'flor', 'hibiscus', 'tropical', 'red', 'rojo'],
  '🌻': ['sunflower', 'girasol', 'flower', 'flor', 'yellow', 'amarillo', 'sun', 'sol'],
  '🌹': ['rose', 'rosa', 'flower', 'flor', 'red', 'rojo', 'love', 'amor', 'romantic', 'romantico'],
  '🌷': ['tulip', 'tulipan', 'flower', 'flor', 'spring', 'primavera'],
  '🌲': ['tree', 'arbol', 'pine', 'pino', 'christmas', 'navidad', 'forest', 'bosque', 'nature', 'naturaleza'],
  '🌳': ['tree', 'arbol', 'nature', 'naturaleza', 'forest', 'bosque', 'green', 'verde'],
  '🌵': ['cactus', 'desert', 'desierto', 'plant', 'planta'],
  '🍀': ['clover', 'trebol', 'luck', 'suerte', 'green', 'verde', 'irish'],
  '🍁': ['maple', 'arce', 'leaf', 'hoja', 'fall', 'otoño', 'canada'],
  '🍂': ['leaf', 'hoja', 'fall', 'otoño', 'autumn'],
  '🍃': ['leaf', 'hoja', 'wind', 'viento', 'green', 'verde', 'nature', 'naturaleza'],
  '🌾': ['wheat', 'trigo', 'grain', 'grano', 'farm', 'granja', 'field', 'campo'],
  '⛰️': ['mountain', 'montaña', 'nature', 'naturaleza', 'climb', 'escalar', 'hike', 'caminar'],
  '🏔️': ['mountain', 'montaña', 'snow', 'nieve', 'nature', 'naturaleza'],
  '🌋': ['volcano', 'volcan', 'mountain', 'montaña', 'fire', 'fuego', 'lava'],
  
  // Objetos de oficina y trabajo
  '💼': ['briefcase', 'maletin', 'work', 'trabajo', 'business', 'negocio', 'office', 'oficina'],
  '📁': ['folder', 'carpeta', 'file', 'archivo', 'office', 'oficina', 'document', 'documento'],
  '📂': ['folder', 'carpeta', 'open', 'abierta', 'file', 'archivo', 'office', 'oficina'],
  '📊': ['chart', 'grafica', 'graph', 'statistics', 'estadisticas', 'data', 'datos', 'business', 'negocio'],
  '📈': ['chart', 'grafica', 'up', 'arriba', 'growth', 'crecimiento', 'increase', 'aumento'],
  '📉': ['chart', 'grafica', 'down', 'abajo', 'decrease', 'disminucion', 'loss', 'perdida'],
  '📋': ['clipboard', 'portapapeles', 'list', 'lista', 'task', 'tarea', 'checklist'],
  '📎': ['paperclip', 'clip', 'attach', 'adjuntar', 'office', 'oficina'],
  '✂️': ['scissors', 'tijeras', 'cut', 'cortar', 'office', 'oficina'],
  '🖊️': ['pen', 'pluma', 'write', 'escribir', 'office', 'oficina'],
  '✏️': ['pencil', 'lapiz', 'write', 'escribir', 'draw', 'dibujar', 'school', 'escuela'],
  '📏': ['ruler', 'regla', 'measure', 'medir', 'school', 'escuela', 'office', 'oficina'],
  '🔍': ['search', 'buscar', 'magnifying', 'lupa', 'find', 'encontrar', 'look', 'mirar'],
  '🔎': ['search', 'buscar', 'magnifying', 'lupa', 'find', 'encontrar', 'zoom'],
  
  // Casa y hogar
  '🏠': ['house', 'casa', 'home', 'hogar', 'building', 'edificio'],
  '🏡': ['house', 'casa', 'home', 'hogar', 'garden', 'jardin'],
  '🏢': ['building', 'edificio', 'office', 'oficina', 'work', 'trabajo', 'city', 'ciudad'],
  '🏥': ['hospital', 'health', 'salud', 'medical', 'medico', 'doctor', 'emergency', 'emergencia'],
  '🏫': ['school', 'escuela', 'building', 'edificio', 'education', 'educacion', 'study', 'estudiar'],
  '🏪': ['store', 'tienda', 'shop', 'compras', 'convenience', 'conveniencia'],
  '🛋️': ['couch', 'sofa', 'furniture', 'mueble', 'living room', 'sala', 'relax', 'descanso'],
  '🪑': ['chair', 'silla', 'furniture', 'mueble', 'sit', 'sentar'],
  '🚪': ['door', 'puerta', 'entrance', 'entrada', 'exit', 'salida', 'house', 'casa'],
  '🪟': ['window', 'ventana', 'house', 'casa', 'home', 'hogar'],
  '🛁': ['bath', 'baño', 'tub', 'tina', 'shower', 'ducha', 'clean', 'limpio'],
  '🚿': ['shower', 'ducha', 'bath', 'baño', 'clean', 'limpio', 'water', 'agua'],
  '🚽': ['toilet', 'inodoro', 'bathroom', 'baño', 'wc'],
  '🧹': ['broom', 'escoba', 'clean', 'limpiar', 'sweep', 'barrer', 'house', 'casa'],
  '🧺': ['basket', 'canasta', 'laundry', 'lavanderia', 'clothes', 'ropa'],
  '🧼': ['soap', 'jabon', 'clean', 'limpiar', 'wash', 'lavar', 'hygiene', 'higiene'],
  
  // Tecnología (nota: se removieron las entradas duplicadas de 💻 y 📱 que estaban en las líneas 361 y 365)
  '🖥️': ['computer', 'computadora', 'desktop', 'escritorio', 'monitor', 'screen', 'pantalla'],
  '⌨️': ['keyboard', 'teclado', 'type', 'escribir', 'computer', 'computadora'],
  '🖱️': ['mouse', 'raton', 'click', 'computer', 'computadora'],
  '📲': ['phone', 'telefono', 'mobile', 'celular', 'call', 'llamar', 'arrow'],
  '📞': ['phone', 'telefono', 'call', 'llamar', 'telephone'],
  '📺': ['tv', 'television', 'tele', 'watch', 'ver', 'screen', 'pantalla'],
  '📻': ['radio', 'music', 'musica', 'listen', 'escuchar'],
  '🎧': ['headphones', 'audifonos', 'music', 'musica', 'listen', 'escuchar', 'audio'],
  '🎤': ['microphone', 'microfono', 'sing', 'cantar', 'speak', 'hablar', 'karaoke'],
  '📷': ['camera', 'camara', 'photo', 'foto', 'picture', 'imagen'],
  '📸': ['camera', 'camara', 'photo', 'foto', 'flash', 'selfie'],
  '📹': ['video', 'camera', 'camara', 'record', 'grabar', 'film', 'filmar'],
  '🔌': ['plug', 'enchufe', 'electric', 'electrico', 'power', 'energia', 'charge', 'cargar'],
  '💡': ['light', 'luz', 'bulb', 'foco', 'idea', 'bright', 'brillante'],
  '🔦': ['flashlight', 'linterna', 'light', 'luz', 'dark', 'oscuro'],
  '⚡': ['lightning', 'rayo', 'electric', 'electrico', 'power', 'energia', 'fast', 'rapido', 'thunder', 'trueno'],
  
  // Tiempo y reloj (nota: se removió la entrada duplicada de ⏰ que estaba en la línea 381)
  '⏱️': ['stopwatch', 'cronometro', 'timer', 'time', 'tiempo', 'sport', 'deporte'],
  '⏲️': ['timer', 'temporizador', 'clock', 'reloj', 'time', 'tiempo', 'cook', 'cocinar'],
  '🕐': ['clock', 'reloj', 'time', 'tiempo', 'hour', 'hora', 'one', 'una'],
  '⌛': ['hourglass', 'reloj de arena', 'time', 'tiempo', 'wait', 'esperar'],
  '⏳': ['hourglass', 'reloj de arena', 'time', 'tiempo', 'loading', 'cargando'],
  
  // Objetos de oficina y trabajo
  
  // Celebraciones
  '🎊': ['confetti', 'celebration', 'celebracion', 'party', 'fiesta'],
  '🎈': ['balloon', 'globo', 'party', 'fiesta', 'birthday', 'cumpleaños', 'celebration', 'celebracion'],
  '🎁': ['gift', 'regalo', 'present', 'birthday', 'cumpleaños', 'christmas', 'navidad'],
  '🎂': ['cake', 'pastel', 'birthday', 'cumpleaños', 'celebration', 'celebracion'],
  '🎄': ['christmas', 'navidad', 'tree', 'arbol', 'holiday', 'festivo', 'december', 'diciembre'],
  '🎃': ['pumpkin', 'calabaza', 'halloween', 'october', 'octubre', 'spooky', 'scary'],
  '🎅': ['santa', 'christmas', 'navidad', 'holiday', 'festivo'],
  '🎆': ['fireworks', 'fuegos artificiales', 'celebration', 'celebracion', 'new year', 'año nuevo'],
  '🎇': ['sparkler', 'bengala', 'fireworks', 'celebration', 'celebracion'],
  '🧨': ['firecracker', 'petardo', 'celebration', 'celebracion', 'explosion'],
  
  // Herramientas
  '🔧': ['wrench', 'llave', 'tool', 'herramienta', 'fix', 'arreglar', 'repair', 'reparar'],
  '🔨': ['hammer', 'martillo', 'tool', 'herramienta', 'build', 'construir', 'fix', 'arreglar'],
  '🪛': ['screwdriver', 'destornillador', 'tool', 'herramienta', 'fix', 'arreglar'],
  '🔩': ['screw', 'tornillo', 'bolt', 'tool', 'herramienta', 'fix', 'arreglar'],
  '⚙️': ['gear', 'engranaje', 'settings', 'configuracion', 'machine', 'maquina'],
  '🛠️': ['tools', 'herramientas', 'fix', 'arreglar', 'repair', 'reparar', 'work', 'trabajo'],
  
  // Manos y gestos
  '👋': ['wave', 'saludar', 'hola', 'hi', 'hello', 'bye', 'adios', 'hand', 'mano'],
  '🤚': ['hand', 'mano', 'stop', 'alto', 'raised', 'levantada'],
  '🖐️': ['hand', 'mano', 'five', 'cinco', 'high five', 'choca'],
  '✋': ['hand', 'mano', 'stop', 'alto', 'high five', 'choca'],
  '👌': ['ok', 'okay', 'bien', 'perfect', 'perfecto', 'good', 'bueno'],
  '🤌': ['pinch', 'pellizco', 'italian', 'italiano', 'chef', 'kiss'],
  '✌️': ['peace', 'paz', 'victory', 'victoria', 'two', 'dos', 'v'],
  '🤞': ['fingers crossed', 'dedos cruzados', 'luck', 'suerte', 'hope', 'esperanza'],
  '🤟': ['love', 'amor', 'rock', 'sign', 'señas'],
  '🤘': ['rock', 'metal', 'horns', 'cuernos', 'cool', 'genial'],
  '🤙': ['call', 'llamar', 'phone', 'telefono', 'hang loose', 'shaka'],
  '👈': ['point', 'señalar', 'left', 'izquierda', 'direction', 'direccion'],
  '👉': ['point', 'señalar', 'right', 'derecha', 'direction', 'direccion'],
  '👆': ['point', 'señalar', 'up', 'arriba', 'direction', 'direccion'],
  '👇': ['point', 'señalar', 'down', 'abajo', 'direction', 'direccion'],
  '☝️': ['point', 'señalar', 'up', 'arriba', 'one', 'uno', 'idea'],
  '👍': ['thumbs up', 'pulgar arriba', 'like', 'me gusta', 'good', 'bueno', 'ok', 'yes', 'si', 'approve', 'aprobar'],
  '👎': ['thumbs down', 'pulgar abajo', 'dislike', 'no me gusta', 'bad', 'malo', 'no', 'disapprove', 'desaprobar'],
  '✊': ['fist', 'puño', 'power', 'poder', 'strong', 'fuerte', 'fight', 'lucha'],
  '👊': ['punch', 'golpe', 'fist bump', 'puño', 'bro', 'power', 'poder'],
  '🤛': ['fist', 'puño', 'bump', 'left', 'izquierda'],
  '🤜': ['fist', 'puño', 'bump', 'right', 'derecha'],
  '👏': ['clap', 'aplaudir', 'applause', 'aplauso', 'bravo', 'congratulations', 'felicidades'],
  '🙌': ['celebrate', 'celebrar', 'hands up', 'manos arriba', 'praise', 'hooray', 'yay'],
  '🫶': ['heart hands', 'manos corazon', 'love', 'amor', 'care', 'cariño'],
  '👐': ['open hands', 'manos abiertas', 'hug', 'abrazo'],
  '🤲': ['palms up', 'palmas arriba', 'receive', 'recibir', 'pray', 'rezar'],
  '🤝': ['handshake', 'apreton de manos', 'deal', 'trato', 'agreement', 'acuerdo', 'partner', 'socio'],
  '🙏': ['pray', 'rezar', 'please', 'por favor', 'thanks', 'gracias', 'hope', 'esperanza', 'namaste'],
  '✍️': ['write', 'escribir', 'sign', 'firmar', 'pen', 'pluma'],
  '💅': ['nails', 'uñas', 'manicure', 'beauty', 'belleza', 'sassy', 'fabulous'],
  '🤳': ['selfie', 'photo', 'foto', 'phone', 'telefono', 'picture', 'imagen'],
  '💪': ['muscle', 'musculo', 'strong', 'fuerte', 'power', 'poder', 'gym', 'gimnasio', 'flex', 'workout', 'ejercicio'],
  '🦵': ['leg', 'pierna', 'kick', 'patada'],
  '🦶': ['foot', 'pie', 'kick', 'patada', 'step', 'paso'],
  '👂': ['ear', 'oreja', 'oido', 'listen', 'escuchar', 'hear', 'oir'],
  '👃': ['nose', 'nariz', 'smell', 'oler'],
  '🧠': ['brain', 'cerebro', 'think', 'pensar', 'smart', 'inteligente', 'mind', 'mente', 'idea'],
  '👀': ['eyes', 'ojos', 'look', 'mirar', 'see', 'ver', 'watch', 'observar'],
  '👁️': ['eye', 'ojo', 'look', 'mirar', 'see', 'ver', 'watch', 'observar'],
  '👅': ['tongue', 'lengua', 'taste', 'probar', 'lick', 'lamer'],
  '👄': ['mouth', 'boca', 'lips', 'labios', 'kiss', 'beso'],
  
  // Personas y profesiones
  '👶': ['baby', 'bebe', 'child', 'niño', 'infant'],
  '👦': ['boy', 'niño', 'child', 'kid', 'son', 'hijo'],
  '👧': ['girl', 'niña', 'child', 'kid', 'daughter', 'hija'],
  '👨': ['man', 'hombre', 'male', 'masculino', 'guy', 'person', 'persona'],
  '👩': ['woman', 'mujer', 'female', 'femenino', 'girl', 'person', 'persona'],
  '👴': ['old man', 'anciano', 'grandfather', 'abuelo', 'elderly', 'viejo'],
  '👵': ['old woman', 'anciana', 'grandmother', 'abuela', 'elderly', 'vieja'],
  '👮': ['police', 'policia', 'cop', 'officer', 'oficial', 'law', 'ley'],
  '👷': ['worker', 'trabajador', 'construction', 'construccion', 'builder', 'constructor'],
  '💂': ['guard', 'guardia', 'soldier', 'soldado', 'british', 'royal'],
  '🕵️': ['detective', 'spy', 'espia', 'investigate', 'investigar', 'secret'],
  '👨‍⚕️': ['doctor', 'medico', 'health', 'salud', 'hospital', 'nurse', 'enfermero'],
  '👩‍⚕️': ['doctor', 'medica', 'health', 'salud', 'hospital', 'nurse', 'enfermera'],
  '👨‍🍳': ['chef', 'cook', 'cocinero', 'food', 'comida', 'kitchen', 'cocina'],
  '👩‍🍳': ['chef', 'cook', 'cocinera', 'food', 'comida', 'kitchen', 'cocina'],
  '👨‍🎓': ['student', 'estudiante', 'graduate', 'graduado', 'school', 'escuela', 'university', 'universidad'],
  '👩‍🎓': ['student', 'estudiante', 'graduate', 'graduada', 'school', 'escuela', 'university', 'universidad'],
  '👨‍💻': ['programmer', 'programador', 'developer', 'desarrollador', 'coder', 'tech', 'tecnologia', 'computer', 'computadora'],
  '👩‍💻': ['programmer', 'programadora', 'developer', 'desarrolladora', 'coder', 'tech', 'tecnologia', 'computer', 'computadora'],
  '👨‍🏫': ['teacher', 'maestro', 'profesor', 'education', 'educacion', 'school', 'escuela'],
  '👩‍🏫': ['teacher', 'maestra', 'profesora', 'education', 'educacion', 'school', 'escuela'],
  '🧑‍🚀': ['astronaut', 'astronauta', 'space', 'espacio', 'nasa', 'rocket', 'cohete'],
  '🧑‍🎨': ['artist', 'artista', 'paint', 'pintar', 'art', 'arte', 'creative', 'creativo'],
  '🧑‍🔬': ['scientist', 'cientifico', 'research', 'investigacion', 'lab', 'laboratorio'],
  '💃': ['dance', 'bailar', 'dancer', 'bailarina', 'party', 'fiesta', 'salsa'],
  '🕺': ['dance', 'bailar', 'dancer', 'bailarin', 'party', 'fiesta', 'disco'],
  '🏃': ['run', 'correr', 'runner', 'corredor', 'exercise', 'ejercicio', 'fast', 'rapido'],
  '🚶': ['walk', 'caminar', 'walking', 'caminando', 'person', 'persona'],
  '🧍': ['stand', 'parado', 'standing', 'person', 'persona'],
  '🧎': ['kneel', 'arrodillado', 'kneeling', 'pray', 'rezar']
};
